[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "faker>=37.12.0",
    "fastapi>=0.120.0",
    "folium>=0.20.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "prophet>=1.2.1",
    "psycopg2-binary>=2.9.11",
    "reportlab>=4.4.4",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.44",
    "streamlit>=1.50.0",
    "streamlit-folium>=0.25.3",
    "uvicorn>=0.38.0",
    "xgboost>=3.1.1",
]
